version: '3'

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
  
  backend:
    build: ./backend
    depends_on:
      - db

  http:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: projet_ws
      POSTGRES_USER: ws_user
      POSTGRES_PASSWORD: ws_password

volumes:
  db-data: