version: "3"

services:
  frontend:
    build: ./frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://ws_user:ws_password@db:5432/projet_ws?schema=public"
      REDIS_HOST: redis
      SECURE_COOKIE: false
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - backend/.env

  http:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: projet_ws
      POSTGRES_USER: ws_user
      POSTGRES_PASSWORD: ws_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ws_user -d projet_ws"]
      interval: 10s
      start_interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      start_period: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
