version: "3"

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

  db:
    image: postgres:16
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: projet_ws
      POSTGRES_USER: ws_user
      POSTGRES_PASSWORD: ws_password

volumes:
  db-data:
